# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Tokyo Trains
tagline:             'A study of colors, shapes & textures found in Japanese train stations.'
description:         'Tokyo Trains is made by Jack Alexander'
url:                 http://lanyon.getpoole.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Jack Alexander
  url:               https://twitter.com/jackalexander_
  email:             contact@jack-alexander.co

# Custom vars
version:             1.0.0

gems:                [jekyll-paginate]
