# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Tokyo Trains
tagline:             'A study of colors, shapes & textures found in Japanese train stations.'
description:         'Tokyo Trains is a study of colors, shapes & textures found in Japanese train stations.'
url:                 http://jack-alexander.github.io/tokyotrains
baseurl:             ''
paginate:            10

# About/contact
author:
  name:              Jack Alexander
  url:               https://twitter.com/jackalexander_
  email:             contact@jack-alexander.co

# Custom vars
version:             0.3

gems:                [jekyll-paginate]
